services:
  - type: worker
    name: Abuseteller_bot
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ABUSEIPDB_API_KEY_1
        sync: false
      - key: ABUSEIPDB_API_KEY_2
        sync: false
